_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 35
                - 41
                - 55
            "2":
                - 1
                - 35
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.11
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 32
learning_rate:
    value: 2.5250716416226626e-05
model_type:
    value: resnet
momentum:
    value: 0.8360881434719252
optimizer:
    value: sgd
trial_number:
    value: 1
