_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 35
                - 41
                - 55
            "2":
                - 1
                - 35
                - 41
                - 55
            "3":
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 32
learning_rate:
    value: 0.0008930927656460215
optimizer:
    value: adam
