_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 35
                - 41
                - 55
            "2":
                - 1
                - 35
                - 41
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.19.11
            "8":
                - 3
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 32
learning_rate:
    value: 0.0002712354804343794
model_type:
    value: resnet
optimizer:
    value: adam
trial_number:
    value: 11
