_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.19.11
            "8":
                - 3
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": windows-amd64
epochs:
    value: 30
learning_rate:
    value: 0.0006707369630642823
optimizer:
    value: adam
